### ISSUE TITLE
Empty folder required to sync.

### ISSUE THREAD

**Issue by kkolk** [Qovery/helm-freeze#1]
After doing an init, if you try to sync without first creating an empty folder it errors with "no such file or directory" here's an example with rabbitmq:

```
helm-freeze sync

[+] Adding helm repos
 -> stable
 -> bitnami

[+] Downloading charts
 -> bitnami/rabbitmq 7.6.4
Error message: rename .//rabbitmq .//rabbitmq.old: no such file or directory% 
```

`mkdir rabbitmq ` and re-executing solves the problem, the .old folder isn't present either after sync is complete.

**Comment by deimosfr** [comment]
Thx it has been fixed
